project_name: fgt

release:
  prerelease: auto
env:
  - GO111MODULE=on
  - CGO_ENABLED=1

builds:
  - id: fgt-darwin-amd64
    hooks:
      pre:
        - chmod +x ./scripts/install-fuse.sh
        - ./scripts/install-fuse.sh
        -  go mod download
    main: .
    binary: fgt
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
  - id: fgt-darwin-arm64
    hooks:
      pre:
        - chmod +x ./scripts/install-fuse.sh
        - ./scripts/install-fuse.sh
        - go mod download
    main: .
    binary: fgt
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
  - id: fgt-linux-amd64
    hooks:
      pre:
        - chmod +x ./scripts/install-fuse.sh
        - ./scripts/install-fuse.sh
        - go mod download
    main: .
    binary: fgt
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
  - id: fgt-linux-arm64
    hooks:
      pre:
        - chmod +x ./scripts/install-fuse.sh
        - ./scripts/install-fuse.sh
        - go mod download
    main: .
    binary: fgt
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
  - id: fgt-windows-amd64
    hooks:
      pre:
        - chmod +x ./scripts/install-fuse.sh
        - ./scripts/install-fuse.sh
        - go mod download
    main: .
    binary: fgt
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -v
      - -trimpath
      - -buildmode=exe
    ldflags:
      - -s -w